# what to claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-volume
spec:
  storageClassName: mylocalstorage 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# where to claim

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-storage
spec:
  storageClassName: mylocalstorage
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: /mnt/historyData1
    type: DirectoryOrCreate
            