kind: Service
apiVersion: v1
metadata:
  name: webapp
spec:
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30080
  selector:
    endpoint: webapp
  type: NodePort

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hah-webapp
spec:
  selector:
    matchLabels:
      endpoint: webapp
  replicas: 1
  template:
    metadata:
      labels:
        endpoint: webapp
    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-webapp-angular:release2
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice






# Service  
---
kind: Service
apiVersion: v1
metadata:
  name: fleetman-queue
spec:
  ports:
    - name: http
      port: 8161
      nodePort: 30010
    - name: endpoint
      port: 61616
  selector:
    endpoint: queue
  type: NodePort

# JMS Message Broker  Apache ActiveMQ
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: queue
spec:
  selector:
    matchLabels:
      endpoint: queue
  replicas: 1
  template:
    metadata:
      labels:
        endpoint: queue
    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-queue:release2

# SIMULATOR 

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hah-simulator
spec:
  selector:
    matchLabels:
      endpoint: simulator
  replicas: 1
  template:
    metadata:
      labels:
        endpoint: simulator
    spec:
      containers:
        - name: simi
          image: richardchesterwood/k8s-fleetman-position-simulator:release2
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice



---
kind: Service
apiVersion: v1
metadata:
  name: fleetman-position-tracker
spec:
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30030
  selector:
    endpoint: tracker
  type: NodePort


---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hah-tacker
spec:
  selector:
    matchLabels:
      endpoint: tracker
  replicas: 1
  template:
    metadata:
      labels:
        endpoint: tracker
    spec:
      containers:
        - name: track
          image: richardchesterwood/k8s-fleetman-position-tracker:release3
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice

---
kind: Service
apiVersion: v1
metadata:
  name: fleetman-api-gateway
spec:
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30040
  selector:
    endpoint: api-gateway
  type: NodePort


---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      endpoint: api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        endpoint: api-gateway
    spec:
      containers:
        - name: gateway
          image: richardchesterwood/k8s-fleetman-api-gateway:release2
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice
                            